- package.json
- plugin.xml
Version 2.0.1を更新
●修正点
プラグインバージョンを 2.0.1に変更(plugin.xmlファイルとpackage.jsonファイル内) 
GooglePlayService GCMのバージョンを8.3 -> 8.1に変更(plugin.xml内)
> update push plugin 2.0.1

- package.json
> updated version number in package.json

- package.json
- plugin.xml
- src/android/NiftyPushPlugin.java
> release of 2.0.3

- package.json
- plugin.xml
- Some fixes for the preparation of release.
- Fixed version number of plugin.
```
Next step: Create a pull request to master from develop.
```
- Check the old version number is nothing in the source code.
```git grep "2.0.3"```
- Check the new version number is available.
```git grep "2.0.4"```
> Preparation of release for v2.0.4

- README.md
- package.json
- plugin.xml
> Update version number on setting files

- plugin.xml
Cordova 6.5に対応するため、新たに導入された-Debug.plistおよび-Release.plistに
aps-environmentを追加します。
（なお、この修正を行うとCordova 6.2系のプロジェクトでは動作しません。
MonacaのCordova 6.5系対応が完了後、Cordova 6.5プロジェク上でご確認ください）
- Fixed #xx
Cordova 6.5プロジェクトを作成
(もしくは、既存のCordova 6.2プロジェクトをアップデートして、Cordova 6.5プロジェクトに
昇格)
本プラグインをカスタムプラグインとして追加し、プロジェクトでdeviceToken設定を行う
```            window.NCMB.monaca.setDeviceToken("08509c3bbdc3759e60e7d279a9765daae005e03b0d22cbf5dbb068511ab2421e",
"db6dc264e8d2f679c80c6d09fc927dc012e8b3737a662dee4daf5ae8a6ced84e",
"699814914739"
, 
function() { …
```
> Dev cordova 6 5

- README.md
- package.json
- plugin.xml
> 2.0.7バージョンアップするための更新

- README.md
> Update support version for plugin v.2.0.7

- ncmb.gradle
利用しているgoogleのライブラリをアップデート
- Fixed #xx
gradleファイル(ncmb.gradle)を変更し、利用している com.android.supportを
support-v4:22.2.1
から
support-v4.23.1+
に変更
不具合ではないので、動作確認手順は特になし。
もともと、Cordova 5.2系と整合性をもたせるために22.2.1を利用していました。
現在、Cordova 6.5系での利用を想定しているため、23系を利用するように変更しました。
> Dev update android support

- package.json
- plugin.xml
> update version to 2.0.8

- package.json
- plugin.xml
> Update version number for 2.0.9

- src/android/NiftyPushPlugin.java
- Fixed #32
Confirm operation.
> fix crash app when set clientKey ""

- package.json
- plugin.xml
> Update version number (2.0.10) to release

- package.json
- plugin.xml
> Update version number to 2.0.11

- README.md
> iOS SDKへの参照を追記

- src/ios/AppDelegate+NifCloud.m
- Fixed #75 
Manual test.
Implement app and send the push notification. Compare the result get notification with v 2.0.9.
> Fix bug #75. Notice is not displayed during application launch

- package.json
- plugin.xml
> Update version to 3.0.3 to Release prepare

- README.md
> Fix support cordova sdk README

- LICENSE
- package.json
- plugin.xml
* Update plugin version to 3.0.4
* Update year of Licence files
> Update version 3.0.4 to release

- package.json
- plugin.xml
> Update plugin version to 3.0.5

- LICENSE
- README.md
- package.json
- plugin.xml
> Release/update v3.0.6

- src/ios/NCMB/NCMBConstants.h
- src/ios/NCMB/NCMBError.h
- src/ios/NCMB/NCMBError.m
- src/ios/NCMB/NCMBPush.m
- src/ios/NCMB/NCMBRequest/NCMBRequest.h
- src/ios/NCMB/NCMBRequest/NCMBRequest.m
- src/ios/NCMB/NCMBRichPush/NCMBRichPushView.h
- src/ios/NCMB/NCMBRichPush/NCMBRichPushView.m
- src/ios/NCMB/NCMBUser.m
- src/ios/NCMB/NCMB_Info.plist
- Fixed #xx
iOS （iOS 13, 11）端末で以下の動作検証を行いました
- 端末登録
- リッチプッシュ通知の配信と受信の挙動
> Feature/update ios 3.0.3

- ncmb.gradle
> Issue #101: remove override target android api

- .github/CONTRIBUTING.md
- README.md
- package.json
- plugin.xml
> Release 3.0.8 prepare

- src/android/NcmbPushPlugin.java
- src/ios/AppDelegate+NifCloud.m
- src/ios/NcmbPushNotification.h
- src/ios/NcmbPushNotification.m
- www/ncmb.js
- Fixed #105
- Confirm operation.
> Issue #105: Monaca push pluginのlocal storage のデバイス更新対応 

- README.md
- package.json
- plugin.xml
> Release 3.0.9 prepare

- README.md
- package.json
- plugin.xml
> Release 3.0.10 prepare

- README.md
- package.json
- plugin.xml
> Release/prepare 3.0.11

- ncmb.gradle
> ticket #321177 migrate to maven central.

- README.md
- package.json
- plugin.xml
> update support version

- plugin.xml
> add android:exported required build on android 12

- README.md
- package.json
- plugin.xml
- リリース番号変更
- サポート環境の追加
- サポートバージョンの確認
> Release prepare 3.1.2

- README.md
> READMEに日本語の説明を追加

- README.md
- 対応するAndroidおよびAndroid SDKのバージョンをREADMEに明記しました。
> Add support_version_android_sdk

- README.md
- サポート環境の更新に合わせて、サポートするSDKバージョンを更新実施
> テクニカルサポートバージョンの更新

- ncmb.gradle
- plugin.xml
- src/android/NcmbPushPlugin.java
- www/ncmb.js
- Android13 プッシュ通知の許可する機能を追加
```
<script>
document.addEventListener("deviceready", function()
{
// プッシュ通知受信時のコールバックを登録します
window.NCMB.monaca.setHandler
(
function(jsonData){
// 送信時に指定したJSONが引数として渡されます
alert("callback :::" + JSON.stringify(jsonData));
}
);
var successCallback = function () {
//端末登録後の処理
};
var errorCallback = function (err) {
//端末登録でエラーが発生した場合の処理
};
// デバイストークンを取得してinstallation登録が行われます
// ※ YOUR_APPLICATION_KEY,YOUR_CLIENT_KEYはニフクラ mobile backendから発行されたAPIキーに書き換えてください
window.NCMB.monaca.setDeviceToken(
"YOUR_APPLICATION_KEY",
"YOUR_CLIENT_KEY",
successCallback,
errorCallback
);
//★追加
window.NCMB.monaca.grantPermission(function(hasPermission){
console.log("Notifications permission was " + (hasPermission ? "granted" : "denied"));
});
// 開封通知登録の設定
// trueを設定すると、開封通知を行う …
```
> Android13対応：プッシュ通知の許可する機能を追加

- LICENSE
- README.md
- package.json
- READMEに `grantPermission`を追加
- v3.2.0 にバージョンアップ
- Copyrightを2023に更新
> Bump version to v3.2.0 

- plugin.xml
- #140 に含める予定の更新内容が漏れていたためHotfix
> Hotfix reflect missing updates of v3.2.0

- README.md
- package.json
- plugin.xml
> Bump version to v3.2.1

- README.md
> iOS17の対応環境を追加

- README.md
- package.json
- plugin.xml
- v3.2.2 へのバージョンアップ
- iOS 17を対応環境に追加
> Bump version to v3.2.2
